### ISSUE TITLE
PartyDataCredential - Name Field

### ISSUE THREAD

**Issue by tsnyder-gs1us** [gs1/VC-Data-Model#1]
The name property in the PartyDataCredential example requires an additional schema context.  Is name a required property for a PartyDataCredential?

`
  "@context": [
           {
                "name": "https://schema.org/name"
            }
]
`

**Comment by mgh128** [comment]
Looking through the code in that repository I don't see anything that appears to be a SHACL validation resource or even a JSON Schema validation resource, so it is currently unclear which properties are required / mandatory.  That typically would not be expressed via the ontology resources.
