### ISSUE TITLE
Naming of PartyDataCredential

### ISSUE THREAD

**Issue by tsnyder-gs1us** [gs1/VC-Data-Model#3]
All the GS1 Credential Types start with GS1 accept PartyDataCredential. Is there a reason why this credential types does not start with GS1?

**Comment by KDean-GS1** [comment]
Bad practice on my part. Credentials that are based on normative names (e.g., GS1PrefixLicenseCredential for the GS1 Prefix) now have GS1 in their names, others don't.

**Comment by tsnyder-gs1us** [comment]
This has been updated to OrganizationDataCredential
