### ISSUE TITLE
What is the purpose of the VerifiedByGS1DataCredential 

### ISSUE THREAD

**Issue by tsnyder-gs1us** [gs1/VC-Data-Model#4]
Looking for clarity between the VerifiedByGS1DataCredential and GS1DataCredential. Both credential have the same fields. 

- What use cases would a VerifiedByGS1DataCredential be used instead of a GS1DataCredential?
- Who can issue VerifiedByGS1DataCredential?

**Comment by KDean-GS1** [comment]
VerifiedByGS1DataCredential was originally a mapping of the Verified by GS1 trade item attributes. As it is not connected to the Verified by GS1 service, it is now ProductDataCredential.
