### ISSUE TITLE
GS1DataCredential and GS1KeyCredential terms missing in trade-item-context

### ISSUE THREAD

**Issue by nissimsan** [gs1/VC-Data-Model#8]
`GS1DataCredential` is defined in https://ref.gs1.org/gs1/vc/declaration-context/, but the example (in section 5.6.1) only includes https://ref.gs1.org/gs1/vc/trade-item-context/ (which defines all the rest of the terms). 

For GS1DataCredential to be defined, either: 
- include it in https://ref.gs1.org/gs1/vc/trade-item-context/
- or include both contexts on the example

Example of the latter option: https://w3id.org/traceability/#GS1DataCredential

`GS1KeyCredential` has the same issue, the term isn't actually defined in the example (section 5.5.1).

**Comment by KDean-GS1** [comment]
It's defined in declaration-context.
